version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: yeoman-generator
    versions:
    - 5.0.0
    - 5.2.0
  - dependency-name: inquirer-npm-name
    versions:
    - 4.0.0
